---
sidebar: sidebar 
permalink: concept_azure_netapp_files.html 
keywords: azure netapp files, cost, price, features, azure netapp files features, anf, supported regions, azure regions, azure netapp files regions 
summary: 'Azure NetApp Files permet aux entreprises de migrer et d"exécuter leurs applications stratégiques, stratégiques ou stratégiques, gourmandes en performances et en latence, dans Azure sans remaniement pour le cloud.' 
---
= Découvrez Azure NetApp Files
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Azure NetApp Files permet aux entreprises de migrer et d'exécuter leurs applications stratégiques, stratégiques ou stratégiques, gourmandes en performances et en latence, dans Azure sans remaniement pour le cloud.



== Caractéristiques

* La prise en charge de plusieurs protocoles permet d'exécuter les applications Linux et Windows de façon transparente dans Azure.
* Plusieurs tiers de performance permettent un alignement étroit avec les exigences de performances des charges de travail.
* Les certifications les plus exigeantes, telles que SAP HANA, le RGPD et HIPPA, permettent la migration des charges de travail les plus exigeantes vers Azure.




== Fonctionnalités supplémentaires dans Cloud Manager

* Migrez des données NFS ou SMB vers Azure NetApp Files directement à partir de Cloud Manager. Les migrations de données sont optimisées par le service Cloud Sync de NetApp. link:concept_cloud_sync.html["En savoir plus >>"].
* Avec la technologie d'intelligence artificielle (IA), Cloud Compliance vous aide à comprendre le contexte des données et à identifier les données sensibles qui résident sur vos comptes Azure NetApp Files. link:concept_cloud_compliance.html["En savoir plus >>"].




== Le coût

https://azure.microsoft.com/pricing/details/netapp/["Voir la tarification Azure NetApp Files"^].

Notez que votre abonnement et vos frais sont gérés par le service Azure NetApp Files et non par Cloud Manager.



== Régions prises en charge

https://cloud.netapp.com/cloud-volumes-global-regions["Affichez les régions Azure prises en charge"^].



== Demande d'accès

Vous devez obtenir l'accès à Azure NetApp Files par https://aka.ms/azurenetappfiles["envoi d'une demande en ligne"^]. Vous devrez attendre l'approbation de l'équipe Azure NetApp Files pour pouvoir continuer.



== Obtenir de l'aide

Pour tout problème de support technique lié à Azure NetApp Files, utilisez le portail Azure pour enregistrer une demande de support auprès de Microsoft. Sélectionnez votre abonnement Microsoft associé et sélectionnez le nom de service *Azure NetApp Files* sous *stockage*. Fournissez les informations restantes nécessaires pour créer votre demande d'assistance Microsoft.

Pour les problèmes liés à Cloud Sync et à Azure NetApp Files, vous pouvez commencer par utiliser votre numéro de série Cloud Sync directement depuis le service Cloud Sync. Vous devez accéder au service Cloud Sync via le lien dans Cloud Manager. https://docs.netapp.com/us-en/cloudsync/reference_additional_info.html["Affichez le processus d'activation du support Cloud Sync"^].



== Liens connexes

* https://cloud.netapp.com/azure-netapp-files["NetApp Cloud Central : Azure NetApp Files"^]
* https://docs.microsoft.com/azure/azure-netapp-files/["Documentation Azure NetApp Files"^]
* https://docs.netapp.com/us-en/cloudsync/index.html["Documentation Cloud Sync"^]

