---
sidebar: sidebar 
permalink: concept_storage_management.html 
keywords: provisioning, capacity management, storage provisioning, manual, automatic, advanced allocation, aggregates, thin provisioning, free space, mode 
summary: Cloud Manager permet une gestion simplifiée et avancée du stockage Cloud Volumes ONTAP. 
---
= Gestion du stockage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Manager permet une gestion simplifiée et avancée du stockage Cloud Volumes ONTAP.


IMPORTANT: Tous les disques et agrégats doivent être créés et supprimés directement de Cloud Manager. Vous ne devez pas effectuer ces actions à partir d'un autre outil de gestion. Cela peut avoir un impact sur la stabilité du système, entraver la possibilité d'ajouter des disques à l'avenir et générer potentiellement des frais de fournisseur de cloud redondant.



== Provisionnement du stockage

Cloud Manager facilite le provisionnement du stockage pour Cloud Volumes ONTAP en achetant des disques et en gérant des agrégats pour vous. Il vous suffit de créer des volumes. Si vous le souhaitez, vous pouvez utiliser une option d'allocation avancée pour provisionner vous-même des agrégats.



=== Provisionnement simplifié

Les agrégats fournissent un stockage cloud aux volumes. Cloud Manager crée des agrégats pour vous lorsque vous lancez une instance et que vous provisionnez des volumes supplémentaires.

Lorsque vous créez un volume, Cloud Manager fait l'une des trois opérations suivantes :

* Il place le volume sur un agrégat existant qui dispose d'un espace libre suffisant.
* Il place le volume sur un agrégat existant en achetant plus de disques pour cet agrégat.
* Il achète des disques pour un nouvel agrégat et place le volume sur cet agrégat.


Cloud Manager détermine où placer un nouveau volume en se base sur plusieurs facteurs : la taille maximale d'un agrégat, l'activation ou non du provisionnement fin et les seuils d'espace disponible pour les agrégats.


TIP: L'administrateur du compte peut modifier les seuils d'espace libre à partir de la page *Paramètres*.



==== Sélection de la taille du disque pour les agrégats dans AWS

Lorsque Cloud Manager crée de nouveaux agrégats pour Cloud Volumes ONTAP dans AWS, il augmente progressivement la taille du disque dans un agrégat, à mesure que le nombre d'agrégats dans le système augmente. Cloud Manager vous permet ainsi d'utiliser la capacité maximale du système avant d'atteindre le nombre maximal de disques de données autorisés par AWS.

Par exemple, Cloud Manager peut choisir les tailles de disque suivantes pour les agrégats dans un système Cloud Volumes ONTAP Premium ou BYOL :

[cols="3*"]
|===
| Numéro d'agrégat | Taille du disque | Capacité d'agrégat max. 


| 1 | 500 Mo. | 3 To 


| 4 | 1 To | 6 To 


| 6 | 2 To | 12 To 
|===
Vous pouvez choisir vous-même la taille du disque en utilisant l'option d'allocation avancée.



=== Allocation avancée

Plutôt que de laisser Cloud Manager gérer les agrégats pour vous, vous pouvez le faire vous-même. link:task_provisioning_storage.html#creating-aggregates["À partir de la page *allocation avancée*"], vous pouvez créer de nouveaux agrégats qui incluent un nombre spécifique de disques, ajouter des disques à un agrégat existant et créer des volumes dans des agrégats spécifiques.



== Gestion de la capacité

L'administrateur du compte peut décider si Cloud Manager vous informe des décisions en matière de capacité de stockage ou si Cloud Manager gère automatiquement les besoins en capacité pour vous. Il peut vous aider à comprendre le fonctionnement de ces modes.



=== Gestion automatique de la capacité

Le mode de gestion de la capacité est défini sur automatique par défaut. Dans ce mode, Cloud Manager achète automatiquement de nouveaux disques pour les instances Cloud Volumes ONTAP lorsque plus de capacité est nécessaire, supprime les ensembles de disques (agrégats) inutilisés, déplace des volumes entre les agrégats si nécessaire et tente de rétablir la panne des disques.

Les exemples suivants illustrent le fonctionnement de ce mode :

* Si un agrégat de 5 disques EBS ou moins atteint le seuil de capacité, Cloud Manager achète automatiquement de nouveaux disques pour cet agrégat afin que les volumes puissent continuer à croître.
* Si un agrégat de 12 disques Azure atteint le seuil de capacité, Cloud Manager déplace automatiquement un volume de cet agrégat vers un agrégat de capacité disponible ou vers un nouvel agrégat.
+
Si Cloud Manager crée un nouvel agrégat pour le volume, il sélectionne une taille de disque qui convient à sa taille.

+
Notez que l'espace libre est désormais disponible sur l'agrégat d'origine. Les volumes existants ou les nouveaux volumes peuvent utiliser cet espace. L'espace ne peut pas être renvoyé vers AWS, Azure ou GCP dans ce scénario.

* Si un agrégat ne contient pas de volumes pendant plus de 12 heures, Cloud Manager le supprime.




==== Gestion des LUN avec gestion automatique de la capacité

La gestion automatique de la capacité de Cloud Manager ne s'applique pas aux LUN. Lorsque Cloud Manager crée un LUN, il désactive la fonctionnalité de croissance automatique.



==== Gestion des inodes avec gestion automatique de la capacité

Cloud Manager surveille l'utilisation d'inode sur un volume. Lorsque 85 % des inodes sont utilisés, Cloud Manager augmente la taille du volume pour augmenter le nombre d'inodes disponibles. Le nombre de fichiers qu'un volume peut contenir est déterminé par le nombre d'inodes qu'il possède.



=== Gestion manuelle de la capacité

Si l'administrateur du compte définit le mode de gestion de la capacité sur manuel, Cloud Manager affiche les messages action requise lorsque les décisions relatives à la capacité doivent être prises. Les mêmes exemples décrits en mode automatique s'appliquent au mode manuel, mais il vous appartient d'accepter les actions.
