---
sidebar: sidebar 
permalink: reference_security_groups_windows_ad_servers.html 
keywords: Cloud Volumes Service for AWS, security groups, ports, protocols, Windows, Active Directory, AD 
summary: 'Si vous utilisez des serveurs Windows Active Directory (AD) avec des volumes clouds, vous devez vous familiariser avec les paramètres des groupes de sécurité AWS. Les paramètres permettent aux volumes cloud de s"intégrer correctement avec AD.' 
---
= Paramètres des groupes de sécurité AWS pour les serveurs Windows AD
:toc: macro
:hardbreaks:
:allow-uri-read: 
:toc: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Si vous utilisez des serveurs Windows Active Directory (AD) avec des volumes clouds, vous devez vous familiariser avec les paramètres des groupes de sécurité AWS. Les paramètres permettent aux volumes cloud de s'intégrer correctement avec AD.

Par défaut, le groupe de sécurité AWS appliqué à une instance Windows EC2 ne contient aucune règle entrante pour un protocole sauf RDP. Vous devez ajouter des règles aux groupes de sécurité associés à chaque instance Windows AD afin d'activer la communication entrante à partir de Cloud Volumes Service. Les ports requis sont les suivants :

[cols="40,30,30"]
|===
| Service | Port | Protocole 


| SERVICES Web PUBLICITAIRES | 9389 | TCP 


| DNS | 53 | TCP 


| DNS | 53 | UDP 


| ICMPv4 | S/O | Réponse écho 


| Kerberos | 464 | TCP 


| Kerberos | 464 | UDP 


| Kerberos | 88 | TCP 


| Kerberos | 88 | UDP 


| LDAP | 389 | TCP 


| LDAP | 389 | UDP 


| LDAP | 3268 | TCP 


| Nom NetBIOS | 138 | UDP 


| SAM/LSA | 445 | TCP 


| SAM/LSA | 445 | UDP 


| Sécurité LDAP | 636 | TCP 


| Sécurité LDAP | 3269 | TCP 


| w32time | 123 | UDP 
|===
Si vous déployez et gérez vos contrôleurs de domaine d'installation AD et vos serveurs membres sur une instance AWS EC2, vous aurez besoin de plusieurs règles de groupe de sécurité pour autoriser le trafic de Cloud Volumes Service. Voici un exemple de mise en œuvre de ces règles pour les applications AD dans le modèle AWS CloudFormation.

[source, json]
----
{
    "AWSTemplateFormatVersion" : "2010-09-09",
    "Description" : "Security Group for AD",
    "Parameters" :
    {
    	"VPC" :
    	{
    		"Type" : "AWS::EC2::VPC::Id",
    		"Description" : "VPC where the Security Group will belong:"
    	},
    	"Name" :
    	{
    		"Type" : "String",
    		"Description" : "Name Tag of the Security Group:"
    	},
    	"Description" :
    	{
    		"Type" : "String",
    		"Description" : "Description Tag of the Security Group:",
            "Default" : "Security Group for Active Directory for CVS "
    	},
        "CIDRrangeforTCPandUDP" :
    	{
    		"Type" : "String",
    		"Description" : "CIDR Range for the UDP ports 445,138,464,389,53,123 and for the TCP ports 464,339,3389,3268,88,636,9389,445 and 0-65535: *CIDR range format: 10.0.0.0/24"
    	}
    },
    "Resources" :
    {
    	"ADSGWest" :
    	{
    		"Type" : "AWS::EC2::SecurityGroup",
    		"Properties" :
    		{
    			"GroupDescription" : {"Ref" : "Description"},
    			"VpcId" : { "Ref" : "VPC" },
                "SecurityGroupIngress" : [
                    {
                        "IpProtocol" : "udp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "445",
                        "ToPort" : "445"
                    },
                    {
                        "IpProtocol" : "udp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "138",
                        "ToPort" : "138"
                    },
                    {
                        "IpProtocol" : "udp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "464",
                        "ToPort" : "464"
                    },
                    {
                        "IpProtocol" : "tcp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "464",
                        "ToPort" : "464"
                    },
                    {
                        "IpProtocol" : "udp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "389",
                        "ToPort" : "389"
                    },
                    {
                        "IpProtocol" : "udp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "53",
                        "ToPort" : "53"
                    },
                    {
                        "IpProtocol" : "tcp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "339",
                        "ToPort" : "339"
                    },
                    {
                        "IpProtocol" : "udp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "123",
                        "ToPort" : "123"
                    },
                    {
                        "IpProtocol" : "tcp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "3389",
                        "ToPort" : "3389"
                    },
                    {
                        "IpProtocol" : "tcp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "3268",
                        "ToPort" : "3268"
                    },
                    {
                        "IpProtocol" : "tcp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "88",
                        "ToPort" : "88"
                    },
                    {
                        "IpProtocol" : "tcp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "636",
                        "ToPort" : "636"
                    },
                    {
                        "IpProtocol" : "tcp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "3269",
                        "ToPort" : "3269"
                    },
                    {
                        "IpProtocol" : "tcp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "53",
                        "ToPort" : "53"
                    },
                    {
                        "IpProtocol" : "tcp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "0",
                        "ToPort" : "65535"
                    },
                    {
                        "IpProtocol" : "tcp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "9389",
                        "ToPort" : "9389"
                    },
                    {
                        "IpProtocol" : "tcp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "445",
                        "ToPort" : "445"
                    }
                ]
    		}
    	}
    },
    "Outputs" :
    {
        "SecurityGroupID" :
        {
            "Description" : "Security Group ID",
            "Value" : { "Ref" : "ADSGWest" }
        }
    }
}
----