---
sidebar: sidebar 
permalink: task_getting_started_azure.html 
keywords: microsoft, azure, netapp, data fabric, hybrid cloud, cloud, public cloud, networking, marketplace, virtual machine, vnet, quick, getting started, install, installing, deploy, deploying, setup, setting up, launching, requirements, prerequisites, cloud central, permissions, custom role, role, json, permissions, virtual machine, video, connectivity, internet, outbound, endpoint, connection, networks, vpn, replicating, policy, iam, setupasservice, sign up, cloud manager, cloud volumes ontap, cloud ontap, subscription, create 
summary: Découvrez Cloud Volumes ONTAP pour Azure en quelques étapes. 
---
= Mise en route de Cloud Volumes ONTAP pour Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Découvrez Cloud Volumes ONTAP pour Azure en quelques étapes.



==== Créer un connecteur

[role="quick-margin-para"]
Si vous n'avez pas de link:concept_connectors.html["Connecteur"] Cependant, un administrateur de compte doit en créer un. link:task_creating_connectors_azure.html["Découvrez comment créer un connecteur dans Azure"].

[role="quick-margin-para"]
Lorsque vous créez votre premier environnement de travail Cloud Volumes ONTAP, Cloud Manager vous invite à déployer un connecteur si vous n'en possédez pas encore.



==== Planification de la configuration

[role="quick-margin-para"]
Cloud Manager propose des packages préconfigurés qui répondent aux exigences de vos workloads, ou vous pouvez créer votre propre configuration. Dans ce dernier cas, il est important de connaître les options dont vous disposez. link:task_planning_your_config_azure.html["En savoir plus >>"].



==== Configurez votre réseau

. Assurez-vous que votre VNet et vos sous-réseaux prennent en charge la connectivité entre le connecteur et Cloud Volumes ONTAP.
. Activez l'accès Internet sortant à partir du réseau vnet cible de sorte que le connecteur et Cloud Volumes ONTAP puissent contacter plusieurs noeuds finaux.
+
Cette étape est importante car le connecteur ne peut pas gérer Cloud Volumes ONTAP sans accès Internet sortant. Si vous devez limiter la connectivité sortante, reportez-vous à la liste des noeuds finaux pour link:reference_networking_azure.html["Le connecteur et le Cloud Volumes ONTAP"].



[role="quick-margin-para"]
link:reference_networking_azure.html["En savoir plus sur les exigences de mise en réseau"].



==== Lancez Cloud Volumes ONTAP à l'aide de Cloud Manager

[role="quick-margin-para"]
Cliquez sur *Ajouter un environnement de travail*, sélectionnez le type de système que vous souhaitez déployer et suivez les étapes de l'assistant. link:task_deploying_otc_azure.html["Lisez les instructions détaillées"].

.Liens connexes
* link:concept_evaluating.html["L'évaluation"]
* link:task_creating_connectors_azure.html["Création d'un connecteur depuis Cloud Manager"]
* link:task_launching_azure_mktp.html["Création d'un connecteur à partir d'Azure Marketplace"]
* link:task_installing_linux.html["Installation du logiciel du connecteur sur un hôte Linux"]
* link:reference_permissions.html#what-cloud-manager-does-with-azure-permissions["Ce que fait Cloud Manager avec les autorisations Azure"]

